# Generated by Django 5.2.3 on 2025-06-24 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('trama', models.TextField()),
                ('cast', models.TextField()),
                ('durata', models.PositiveIntegerField(help_text='Durata in minuti')),
                ('genere', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Film',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('numero_posti', models.PositiveIntegerField()),
                ('file', models.PositiveIntegerField(help_text='Numero di file')),
                ('posti_per_fila', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Sale',
            },
        ),
        migrations.CreateModel(
            name='Proiezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proiezioni', to='film.film')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proiezioni', to='film.sala')),
            ],
            options={
                'verbose_name_plural': 'Proiezioni',
                'ordering': ['data_ora'],
            },
        ),
    ]
