# Generated by Django 5.2.3 on 2025-07-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloutente',
            name='immagine_profilo',
            field=models.ImageField(blank=True, null=True, upload_to='immagini_profili/'),
        ),
    ]
