# Generated by Django 5.2.3 on 2025-06-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0002_commento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commento',
            name='data_commento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='commento',
            name='testo',
            field=models.TextField(max_length=100),
        ),
    ]
