# Generated by Django 5.2.3 on 2025-06-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0005_discussione_messaggio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloutente',
            name='scadenza_abbonamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discussione',
            name='data_creazione',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='data_invio',
            field=models.DateTimeField(),
        ),
    ]
